import React from "react";
import { Pressable, StyleSheet, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { AppText } from "./ui/typography";
import { useAppTheme } from "../contexts/ThemeContext";
import { AdminDashboardStats } from "../services/adminService";
import { formatCurrency } from "../utils/formatters";

export default function VisualAnalyticsDashboard({ stats, months, onMonthsChange, onNavigate }: { stats: AdminDashboardStats; months: 6 | 12; onMonthsChange: (months: 6 | 12) => void; onNavigate?: (screen: string) => void }) {
  const { theme } = useAppTheme();
  const maxRevenue = Math.max(1, ...stats.revenueSeries.map((item) => item.value));
  const composition = stats.revenueComposition;
  const totalComposition = Math.max(1, composition.rent + composition.utilities + composition.services);
  return <View style={styles.container}>
    <View style={[styles.card, { backgroundColor: theme.surfaceElevated }]}>
      <View style={styles.header}><View><AppText style={[styles.eyebrow, { color: theme.muted }]}>DÒNG TIỀN THỰC THU</AppText><AppText style={[styles.value, { color: theme.text }]}>{formatCurrency(stats.totalRevenue)}</AppText></View><View style={[styles.segment, { backgroundColor: theme.background }]}>{([6, 12] as const).map((value) => <Pressable key={value} onPress={() => onMonthsChange(value)} style={[styles.segmentItem, months === value && { backgroundColor: theme.primary }]}><AppText style={[styles.segmentText, { color: months === value ? theme.background : theme.muted }]}>{value}T</AppText></Pressable>)}</View></View>
      <View style={styles.chart}>{stats.revenueSeries.map((item) => <View key={item.period} style={styles.column}><View style={[styles.track, { backgroundColor: theme.background }]}><View style={[styles.bar, { height: `${Math.max(3, item.value / maxRevenue * 100)}%`, backgroundColor: theme.primary }]} /></View><AppText style={[styles.chartLabel, { color: theme.muted }]}>{item.label}</AppText></View>)}</View>
    </View>
    <View style={styles.row}>
      <Pressable onPress={() => onNavigate?.("invoice")} style={[styles.half, { backgroundColor: theme.surfaceElevated }]}><Ionicons name="wallet-outline" size={21} color={theme.danger} /><AppText style={[styles.smallLabel, { color: theme.muted }]}>CÔNG NỢ</AppText><AppText style={[styles.halfValue, { color: theme.text }]}>{formatCurrency(stats.outstandingDebt)}</AppText><AppText style={[styles.detail, { color: theme.danger }]}>{formatCurrency(stats.overdueDebt)} quá hạn</AppText></Pressable>
      <View style={[styles.half, { backgroundColor: theme.surfaceElevated }]}><Ionicons name="checkmark-circle-outline" size={21} color={theme.primary} /><AppText style={[styles.smallLabel, { color: theme.muted }]}>ĐÚNG HẠN</AppText><AppText style={[styles.halfValue, { color: theme.text }]}>{stats.paymentPerformance.onTimeRate}%</AppText><AppText style={[styles.detail, { color: theme.muted }]}>{stats.paymentPerformance.paid} đã thu · {stats.paymentPerformance.unpaid} chờ</AppText></View>
    </View>
    <View style={[styles.card, { backgroundColor: theme.surfaceElevated }]}><AppText style={[styles.eyebrow, { color: theme.muted }]}>CƠ CẤU DOANH THU</AppText>{([{ key: "rent", label: "Tiền phòng", color: theme.primary }, { key: "utilities", label: "Điện nước", color: theme.warning }, { key: "services", label: "Dịch vụ", color: "#3B82F6" }] as const).map((item) => <View key={item.key} style={styles.compositionRow}><View style={styles.compositionHeader}><AppText style={[styles.compositionLabel, { color: theme.text }]}>{item.label}</AppText><AppText style={[styles.compositionValue, { color: theme.text }]}>{formatCurrency(composition[item.key])}</AppText></View><View style={[styles.progress, { backgroundColor: theme.background }]}><View style={{ width: `${composition[item.key] / totalComposition * 100}%`, height: "100%", borderRadius: 999, backgroundColor: item.color }} /></View></View>)}</View>
    <View style={[styles.card, { backgroundColor: theme.surfaceElevated }]}><View style={styles.utilityTitle}><View><AppText style={[styles.eyebrow, { color: theme.muted }]}>TIÊU THỤ ĐIỆN NƯỚC</AppText><AppText style={[styles.detail, { color: theme.muted }]}>Dữ liệu từ hóa đơn đã phát hành</AppText></View><Ionicons name="pulse-outline" size={21} color={theme.primary} /></View>{stats.utilitySeries.length ? stats.utilitySeries.map((item) => <View key={item.period} style={styles.utilityRow}><AppText style={[styles.utilityMonth, { color: theme.text }]}>{item.label}</AppText><AppText style={[styles.utilityValue, { color: theme.warning }]}>{item.electricity} kWh</AppText><AppText style={[styles.utilityValue, { color: "#3B82F6" }]}>{item.water} m³</AppText></View>) : <AppText style={[styles.empty, { color: theme.muted }]}>Chưa có hóa đơn điện nước trong kỳ.</AppText>}</View>
  </View>;
}

const styles = StyleSheet.create({
  container: { gap: 12 }, card: { borderRadius: 20, padding: 16 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, eyebrow: { fontSize: 10.5, fontWeight: "900", letterSpacing: .8 }, value: { fontSize: 25, fontWeight: "900", marginTop: 4 }, segment: { padding: 3, borderRadius: 10, flexDirection: "row" }, segmentItem: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 8 }, segmentText: { fontSize: 10, fontWeight: "900" },
  chart: { height: 132, flexDirection: "row", alignItems: "flex-end", gap: 7, marginTop: 18 }, column: { flex: 1, height: "100%", alignItems: "center", justifyContent: "flex-end" }, track: { flex: 1, width: "100%", borderRadius: 7, justifyContent: "flex-end", overflow: "hidden" }, bar: { width: "100%", borderRadius: 7 }, chartLabel: { fontSize: 8.5, fontWeight: "800", marginTop: 6 },
  row: { flexDirection: "row", gap: 12 }, half: { flex: 1, minHeight: 130, borderRadius: 18, padding: 15 }, smallLabel: { fontSize: 9.5, fontWeight: "900", letterSpacing: .6, marginTop: 12 }, halfValue: { fontSize: 18, fontWeight: "900", marginTop: 4 }, detail: { fontSize: 10.5, lineHeight: 15, marginTop: 3 }, compositionRow: { marginTop: 14 }, compositionHeader: { flexDirection: "row", justifyContent: "space-between" }, compositionLabel: { fontSize: 12, fontWeight: "800" }, compositionValue: { fontSize: 11, fontWeight: "900" }, progress: { height: 8, borderRadius: 999, overflow: "hidden", marginTop: 7 }, utilityTitle: { flexDirection: "row", justifyContent: "space-between" }, utilityRow: { minHeight: 42, flexDirection: "row", alignItems: "center" }, utilityMonth: { width: 68, fontSize: 11, fontWeight: "900" }, utilityValue: { flex: 1, textAlign: "right", fontSize: 11, fontWeight: "800" }, empty: { paddingVertical: 24, textAlign: "center", fontSize: 12 },
});
