"use client";

import { formatCurrency } from "@/lib/formatters";
import type { DashboardStats } from "@/lib/dashboard";

export function VisualAnalyticsDashboard({ stats, months, onMonthsChange }: { stats: DashboardStats; months: 6 | 12; onMonthsChange: (value: 6 | 12) => void }) {
  const maxRevenue = Math.max(1, ...stats.revenueSeries.map((item) => item.value));
  const composition = stats.revenueComposition;
  const compositionTotal = Math.max(1, composition.rent + composition.utilities + composition.services);
  return <div className="space-y-5">
    <section className="rounded-[24px] border border-border bg-card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-muted-foreground">Dòng tiền thực thu</p><h2 className="mt-1 text-3xl font-black">{formatCurrency(stats.totalRevenue)}</h2></div><div className="flex rounded-xl bg-muted p-1">{([6, 12] as const).map((value) => <button key={value} type="button" onClick={() => onMonthsChange(value)} className={`rounded-lg px-3 py-2 text-xs font-black ${months === value ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}>{value} tháng</button>)}</div></div><div className="mt-8 flex h-52 items-end gap-3">{stats.revenueSeries.map((item) => <div key={item.period} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="flex-1 rounded-lg bg-muted flex items-end overflow-hidden"><div className="w-full rounded-lg bg-primary" style={{ height: `${Math.max(2, item.value / maxRevenue * 100)}%` }} /></div><span className="text-center text-[10px] font-bold text-muted-foreground">{item.label}</span></div>)}</div></section>
    <div className="grid gap-5 lg:grid-cols-3"><Metric label="Công nợ chưa thu" value={formatCurrency(stats.outstandingDebt)} detail={`${formatCurrency(stats.overdueDebt)} quá hạn`} tone="text-rose-500" /><Metric label="Thanh toán đúng hạn" value={`${stats.paymentPerformance.onTimeRate}%`} detail={`${stats.paymentPerformance.paid} đã thu · ${stats.paymentPerformance.unpaid} chờ`} tone="text-primary" /><Metric label="Sẵn sàng chốt số" value={`${stats.utilityReading.readyRooms}/${stats.utilityReading.totalOccupiedRooms}`} detail={stats.utilityReading.missingRooms ? `Thiếu ${stats.utilityReading.missingRoomCodes.join(", ")}` : "Tất cả phòng đã đủ số"} tone="text-amber-500" /></div>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-[24px] border border-border bg-card p-6"><p className="text-xs font-black uppercase tracking-wider text-muted-foreground">Cơ cấu doanh thu</p>{([{ key: "rent", label: "Tiền phòng", color: "bg-primary" }, { key: "utilities", label: "Điện nước", color: "bg-amber-500" }, { key: "services", label: "Dịch vụ", color: "bg-blue-500" }] as const).map((item) => <div key={item.key} className="mt-5"><div className="flex justify-between text-sm"><span className="font-bold">{item.label}</span><span className="font-black">{formatCurrency(composition[item.key])}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${item.color}`} style={{ width: `${composition[item.key] / compositionTotal * 100}%` }} /></div></div>)}</section><section className="rounded-[24px] border border-border bg-card p-6"><p className="text-xs font-black uppercase tracking-wider text-muted-foreground">Tiêu thụ điện nước</p><div className="mt-4 space-y-2">{stats.utilitySeries.length ? stats.utilitySeries.map((item) => <div key={item.period} className="grid grid-cols-3 rounded-xl bg-muted/50 px-4 py-3 text-sm"><span className="font-black">{item.label}</span><span className="text-right font-bold text-amber-500">{item.electricity} kWh</span><span className="text-right font-bold text-blue-500">{item.water} m³</span></div>) : <p className="py-10 text-center text-sm text-muted-foreground">Chưa có hóa đơn điện nước trong kỳ.</p>}</div></section></div>
  </div>;
}

function Metric({ label, value, detail, tone }: { label: string; value: string; detail: string; tone: string }) { return <section className="rounded-[20px] border border-border bg-card p-5"><p className="text-xs font-black uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-black">{value}</p><p className={`mt-1 text-xs font-bold ${tone}`}>{detail}</p></section>; }
